apiVersion: batch/v1
kind: Job
metadata:
  name: pi
spec:
  template:
    spec:
      containers:
      - name: pi
        image: alpine:latest
        command: [ "sh", "-c", "while true; do echo Its $(date); sleep 1; done" ]
      restartPolicy: Never
  backoffLimit: 4
