apiVersion: batch/v1
kind: Job
metadata:
  name: timer
spec:
  template:
    spec:
      containers:
      - name: timer
        image: docker.io/tetchel/timer:latest
        # https://stackoverflow.com/questions/43969743/logs-in-kubernetes-pod-not-showing-up
        env:
        - name: PYTHONUNBUFFERED
          value: "0"
        command: [ "python", "/timer.py", "5" ]
      restartPolicy: Never
  backoffLimit: 4
